ruby '>=2.3.1'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~> 4.4.0'
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.1'
gem 'middleman-sprockets', '~> 4.1.1'
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.5.1'
gem 'nokogiri', '~> 1.13.9'
gem 'sprockets', '~> 4.2', '>= 4.2.0'
gem "sass", "~> 3.7"
